# Generated by Django 2.2.7 on 2019-12-05 23:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100, verbose_name='书名')),
                ('book_author', models.CharField(default='', max_length=100, verbose_name='作者')),
                ('book_press', models.CharField(default='', max_length=100, verbose_name='出版社')),
                ('book_isbn', models.CharField(default='', max_length=100, verbose_name='ISBN')),
                ('book_language', models.CharField(default='中文', max_length=100, verbose_name='语言')),
                ('book_price', models.FloatField(default=0.0, verbose_name='价格')),
                ('book_publish_date', models.DateField(default='1999-12-31', verbose_name='出版日期')),
                ('book_number', models.PositiveSmallIntegerField(default=1, verbose_name='数量')),
                ('book_category_choice', models.CharField(choices=[('technology', '科技'), ('literature', '文学'), ('culture', '文化'), ('language', '语言'), ('history', '历史'), ('philosophy', '哲学'), ('medicine', '医学'), ('society', '社会')], default='literature', max_length=100, verbose_name='主题')),
                ('book_summary', models.TextField(default='', verbose_name='内容简介')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'ordering': ['-book_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=100, verbose_name='密码')),
                ('user_phone', models.CharField(max_length=100, verbose_name='手机号')),
                ('user_birthday', models.DateField(default=datetime.datetime(2019, 12, 5, 23, 59, 36, 128490), verbose_name='生日')),
                ('user_gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=100, verbose_name='性别')),
                ('user_email', models.CharField(max_length=100, verbose_name='邮件地址')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-user_id'],
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_time', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 23, 59, 36, 129489))),
                ('return_time', models.DateTimeField(null=True)),
                ('is_return', models.CharField(default='True', max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locallibrary.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locallibrary.User')),
            ],
            options={
                'ordering': ['-return_time'],
            },
        ),
    ]
